name: Run Benchee

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [21.3, 22.3]
        elixir: [1.9.4, 1.10.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install → Compile dependencies
        run: mix do deps.get, compile
      - name: Run Benchmarks
        run: mix do ensure_output_folder_exists, all_benchmarks
